### ISSUE TITLE
Error when running the app

### ISSUE THREAD

**Issue by ShadyStego** [opentok/opentok-react-native-samples#59]
Hi, 

I'm following the instructions and when I ran `npm run ios`, it errored because the script is not defined on package.json. I also tried `react-native run-ios`, and got the following error: 

```
error Could not find iPhone X simulator
debug Error: Could not find iPhone X simulator

at runOnSimulator (/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:131:11)
    at Object.runIOS [as func] (/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/@react-native-community/cli/build/commands/runIOS/runIOS.js:96:10)
    at Promise.resolve.then (/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/@react-native-community/cli/build/cliEntry.js:152:22)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11

```

I'm on XCode 11.7. Initially when I cloned this repo, the react version was `16.8.6`, but when I did `npm install` the console recommends me to change the version to `16.8.3` as the peer dependency . Other than that I didn't make any changes. 

Edit: I ran `npm audit fix` and now getting the following error after running `react-native run-ios`: 
 
```error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - opentok-react-native (to unlink run: "react-native unlink opentok-react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Found Xcode workspace "BasicVideoChat.xcworkspace"
info Building (using "xcodebuild -workspace BasicVideoChat.xcworkspace -configuration Debug -scheme BasicVideoChat -destination id=A6499A57-6EC8-48D7-9772-C1B774323C7D")
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening BasicVideoChat.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace BasicVideoChat.xcworkspace -configuration Debug -scheme BasicVideoChat -destination id=A6499A57-6EC8-48D7-9772-C1B774323C7D

note: Using new build system
note: Planning build
note: Constructing build description
CreateBuildDirectory /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex (in target 'Pods-BasicVideoChat' from project 'Pods')
    cd /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods
    builtin-create-build-directory /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex

CreateBuildDirectory /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products (in target 'Pods-BasicVideoChat' from project 'Pods')
    cd /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods
    builtin-create-build-directory /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products

CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'OpenTokReactNative' from project 'OpenTokReactNative')
    cd /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name OpenTokReactNative -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/Objects-normal/x86_64/OpenTokReactNative.SwiftFileList -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk -target x86_64-apple-ios9.0-simulator -g -module-cache-path /Users/trisianto/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Index/DataStore -swift-version 4.2 -I /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator -F /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator -F /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/OpenTok -c -j4 -output-file-map /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/Objects-normal/x86_64/OpenTokReactNative-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/Objects-normal/x86_64/OpenTokReactNative.swiftmodule -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-generated-files.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-own-target-headers.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-all-target-headers.hmap -Xcc -iquote -Xcc /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-project-headers.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/Headers/Public -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources-normal/x86_64 -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources/x86_64 -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/Objects-normal/x86_64/OpenTokReactNative-Swift.h -import-objc-header /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios/OpenTokReactNative/OpenTokReactNative-Bridging-Header.h -pch-output-dir /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/PrecompiledHeaders -working-directory /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios

PrecompileSwiftBridgingHeader normal x86_64 (in target 'OpenTokReactNative' from project 'OpenTokReactNative')
    cd /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -target x86_64-apple-ios9.0-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk -I /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator -F /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator -F /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/OpenTok -enable-testing -g -module-cache-path /Users/trisianto/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 4.2 -enforce-exclusivity=checked -Onone -serialize-debugging-options -Xcc -working-directory -Xcc /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios -enable-anonymous-context-mangled-names -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-generated-files.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-own-target-headers.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-all-target-headers.hmap -Xcc -iquote -Xcc /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/OpenTokReactNative-project-headers.hmap -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/ios/Pods/Headers/Public -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources-normal/x86_64 -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources/x86_64 -Xcc -I/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/OpenTokReactNative.build/Debug-iphonesimulator/OpenTokReactNative.build/DerivedSources -Xcc -DDEBUG=1 -serialize-diagnostics-path /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/PrecompiledHeaders/OpenTokReactNative-Bridging-Header-287VFASSG4DUM.dia /Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios/OpenTokReactNative/OpenTokReactNative-Bridging-Header.h -index-store-path /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Index/DataStore -emit-pch -pch-output-dir /Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/PrecompiledHeaders
/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios/OpenTokReactNative/OpenTokReactNative-Bridging-Header.h:4:9: error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/trisianto/Library/Developer/Xcode/DerivedData/BasicVideoChat-dknujpsizwkzuvbqeuecfsueevvu/Build/Intermediates.noindex/PrecompiledHeaders/OpenTokReactNative-Bridging-Header-swift_3QFX10MREY2SX-clang_30G0YHN38IHAU.pch' for bridging header '/Users/trisianto/Projects/opentok-react-native-samples/BasicVideoChat/node_modules/opentok-react-native/ios/OpenTokReactNative/OpenTokReactNative-Bridging-Header.h'

<unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)

2020-09-12 20:05:24.824 xcodebuild[22944:2260744] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2020-09-12 20:05:24.824 xcodebuild[22944:2260744] Failed to load plugin at: /Users/trisianto/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
** BUILD FAILED **


The following build commands failed:
	PrecompileSwiftBridgingHeader normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by abdulajet** [comment]
Please check the lastest version of the projects if you are still having this issue
